### PR TITLE
Adding pre post keyword arguments to trialization

### PR DESCRIPTION
**Pull request by jthermiz**
Add `pre_stim` and `post_stim` keyword arguments to extract additional time outside of stim_onset and stim_offset

### CODE REVIEW

**Comment by jihyunbak** [comment]
@jthermiz What is the extra output `t` and why/when do you need it?

In any case, I suggest renaming `t` to make it more interpretive.

As for the logic for getting `t`:

- My personal preference is to add a separate method or function that does `t = some_function(self.intervals, pre_stim, post_stim)`, outside the `get_response_matrix`. It seems like `t` is currently calculated from each trial and only the last value is returned.
- Or if you really want `t` to be an output from `get_response_matrix`, I suggest making it an optional output that is returned only when requested explicitly. For example, we could add a keyword argument `return_t` (rename appropriately) that defaults to False, and do:

    ```python
    if return_t:
        return response_list, baseline_list, t
    return response_list, baseline_list
    ```

**Comment by jthermiz** [comment]
@jihyunbak Thanks for the review. Per your suggestion, I made a separate method within the NSDSNWBAudio parent class for returning the time array (the relative time with respect to the stimulus onset).

**Comment by jihyunbak** [comment]
@jthermiz Having a separate method looks good to me!

But I am still confused ... the current output from `get_time_array` divides a single trial duration (plus some pre- and post-stim offset) by the number of samples. Where is this needed?

EDIT: ah, maybe I was confused because in the stimulus metadata, we use `nsamples` = number of trials. So this `num_samples` is just a sub-sampling of the single trial interval, where `num_samples` is a new variable that is unrelated to the stimulus structure?

**Comment by jihyunbak** [comment]
Looks good to me otherwise!

**Comment by jthermiz** [comment]
@jihyunbak `num_samples` is the number of timepoints in a trial so it depends on the stimulus duration, given by intervals and pre- and post_stim the extra time that the user may want to pull. `get_time_array` returns the timepoints in units of seconds which can be used for plotting and other analyses.

**Pull request merged**
